version: '3'
services:
  hk-mysql-1:
    container_name: hk-mysql
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: hellokoding
      MYSQL_ROOT_HOST: '%'
    ports:
    - "3306:3306"
    restart: always
  crud-mysql-vuejs-1:
    IMAGE
    build: .
    ports:
    - 8080:8080
    labels:
     kompose.service.type: NodePort
    command: mvn clean spring-boot:run
    depends_on:
    - hk-mysql
